<?php

namespace AppBundle\Repository;

/**
 * CurrentGameQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentGameQuestionsRepository extends \Doctrine\ORM\EntityRepository
{
}
