<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveGameByUser(User $user)
    {
        $query = $this->createQueryBuilder('g')
            ->where('g.firstUser = :user')
            ->orWhere('g.secondUser = :user')
            ->andWhere('g.status = 3')
            ->setParameter('user', $user)
            ->orderBy('g.id')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $query;
    }

    public function findRatingUsers($id) {

        $query = $this->getEntityManager()->createQuery(
            'SELECT  IDENTITY(g.winner) as winner, count(g.id) as rating
            FROM AppBundle\Entity\Game g
            WHERE g.status = 4
            GROUP BY g.winner
            ORDER BY rating DESC'
        )->setMaxResults($id);

        $rating  = $query->getArrayResult();

        return $rating;
    }
}
