<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandomQuestions(int $limit)
    {
        $query = $this->_em->createQuery(
            'SELECT q
            FROM AppBundle:Question q
            ORDER BY RAND()
            LIMIT :limit'
        )->setParameter('limit', $limit)->getResult();

        return $query;
    }
}