<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByImportIdAndProviderId(User $user)
    {
        return parent::findOneBy([
            'importId' => $user->getImportId(), 'providerId' => $user->getProviderId()
        ]);
    }
}
