# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    sender_vk_service:
        class: AppBundle\Services\MessageSenders\MessageSenderVK
        arguments: ['%peer_id%', '%access_token%', '%v%']
    message_parser_service:
        class: AppBundle\Services\MessageParser
    message_driver_service:
        class: AppBundle\Services\MessageDriver
        arguments: ['@sender_vk_service']
    find_game_service:
        class: AppBundle\Services\Game\Event\GameSearchEvent
        arguments: [ "@doctrine.orm.entity_manager", "@founded_game_service"]

    founded_game_service:
        class: AppBundle\Services\Game\Listeners\GameSearchListener
        arguments: [ "@doctrine.orm.entity_manager", "@sender_vk_service"]