# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    vk_service:
        class: AppBundle\Services\ProviderServices\VkService
        arguments: ['%access_token_vk%']
    tg_service:
        class: AppBundle\Services\ProviderServices\TgService
        arguments: ['%access_token_tg%']
    message_parser_service:
        class: AppBundle\Services\MessageParser
    message_driver_service:
        class: AppBundle\Services\MessageDriver
        arguments: ['@vk_service', '@tg_service', '@doctrine.orm.entity_manager']
