# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    sender_vk_service:
        class: AppBundle\Services\MessageSenders\MessageSenderVK
        arguments: ['%peer_id%', '%access_token%', '%v%']
    message_parser_service:
        class: AppBundle\Services\MessageParser